name: tickeo
description: "Tickeo - App para dividir cuentas automáticamente"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Dependencias básicas que funcionan en web
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  uuid: ^4.2.1
  intl: ^0.19.0
  
  # Dependencias para compartir
  share_plus: ^7.2.2
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.2
  
  # Dependencias para persistencia
  shared_preferences: ^2.2.2
  
  # OCR and Camera dependencies
  image_picker: ^1.0.4
  google_mlkit_text_recognition: ^0.10.0
  camera: ^0.10.5+5
  qr_code_scanner: ^1.0.1
  permission_handler: ^11.1.0
  
  # Universal OCR dependencies
  http: ^1.1.0
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
